minimized:
  title: Project
  description: Power BI Custom Visual
  link: https://github.com/SAIFAS-BI/saifas-pbi-cv-project-support-source/issues
  detailsLink:
  image: /assets/graphics/images/content/saifas-bi-powerbi-custom-visuals/saifas-bi-pbi-cv-project-120px-120px.png
detailed: