#theme:
title: SAIFAS BI
description: SAIFAS BI Projects
url: https://saifas-bi.github.io
author: SAIFAS BI
google_analytics: UA-[]
highlighter: none
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
powerBIcustomVisualsTitle: 'Power BI custom visuals'
powerBIcustomVisualsUrl: '/powerbi/custom-visuals'
powerBIReportsTitle: 'Power BI reports'
powerBIReportsUrl: '/powerbi/reports'
collections:
  - collection-powerbi-engineering-activities
  - collection-powerbi-custom-visuals
  - collection-powerbi-reports
exclude:
- docker-compose.yml
