#theme:
title: SAIFAS BI
description: SAIFAS BI Projects
url: https://saifas-bi.github.io
author: SAIFAS BI
google_analytics: UA-[]
plugins:
  - jekyll-seo-tag
customVisualsUrl: '/powerbi/custom-visuals/'
customVisualsTitle: 'Power BI custom visuals'
customVisualsReportsTitle: 'Power BI showcase sample reports'
