#theme:
title: SAIFAS BI
description: SAIFAS BI Projects
url: https://saifas-bi.github.io
author: SAIFAS BI
google_analytics: UA-[]
highlighter: none
plugins:
  - jekyll-seo-tag
customVisualsUrl: '/powerbi/custom-visuals'
customVisualsTitle: 'Power BI custom visuals'
customVisualsReportsTitle: 'Power BI showcase sample reports'
posts-cards-powerbi-custom-visuals: '/_posts/powerbi-custom-visuals'
collections:
  - collection-powerbi-engineering-activities
  - collection-powerbi-custom-visuals
  - collection-powerbi-reports
