# Site Info and Build settings
---
name: saifas-bi-website
version: 0.5.1
lang: en_US
author: SAIFAS
email: info@saifas.org
about: SAIFAS BI website
copyright: © SAIFAS


repository: "https://github.com/SAIFAS-BI/SAIFAS-BI.github.io"


title: SAIFAS BI
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: https://saifas-bi.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog


logo: "/assets/graphics/images/domain/saifas-bi/logos/saifas-brand-logo-star-theme-blue-black-276px-269px.png"
favicon: "/assets/graphics/images/domain/saifas-bi/icons/fav-icons/saifas-brand-logo-star-theme-blue-black-256px-256px.ico"


timezone: Europe/Moscow


google_analytics: UA-[-]
google_site_verification: [-]

highlighter: none

theme: jekyll-theme-saifas-it


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  news:
    output: true

defaults:
  -
    scope:
      path: _powerbi-engineering-activities
      type: powerbi-engineering-activities
    values:
      layout:
      category: someitems1
      permalink: "/press-updates/:collection/:categories/:title/"
  -
    scope:
      path: _powerbi-custom-visuals
      type: powerbi-custom-visuals
    values:
      layout:
      category: someitems2
      permalink: "/press-updates/:collection/:categories/:title/"
  -
    scope:
      path: _powerbi-reports
      type: powerbi-reports
    values:
      layout:
      category: someitems3
      permalink: "/press-updates/:collection/:categories/:title/"
  -
    scope:
      path: _news
      type: news
    values:
      layout: news-item
      category: hotnews
      permalink: /press-updates/:collection/:categories/:year/:month/:day/:title/


sass:
  sass_dir: ./assets/styles/sass/_sass/

source                        : ./

destination                   : ../app-build-static/
# keep_files:
#   - assets


# includes_dr                   : ./jekyll-stack/templates/_includes/ #doesn't support by jekyll
layouts_dir                   : ./templates/_layouts/
#plugins_dir                   : ./_plugins/
collections_dir               : ./contents/collections/


# Include
# Include to processing.
#
include:
  - assets

contents_root_path: /contents/
contents_pages_path: /contents/pages/

# Exclude
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
- Gemfile*
- Gemfile.lock
- docker-compose.yml
- .sass-cache/
# - .jekyll-cache/
# - Rakefile
# - gemfiles/
# - node_modules/
# - vendor/bundle/
# - vendor/cache/
# - vendor/gems/
# - vendor/ruby/
# - README.md
- /assets/styles/css/readme.md
- /assets/scripts/js/readme.md
- /assets/graphics/fonts/readme.md
# - changelog.md
# - "*.Rmd"
# - .travis.yml
# - node_modules/uglifier/index.js

layout: 
  header:
    logo:
      path: /assets/graphics/images/domain/saifas-bi/logos/saifas-brand-logo-star-theme-blue-black-276px-269px.png
    links:
      -
        title: Experience
        url: "#experience"
      -
        title: Consulting
        url: "#consulting"
      -
        title: Portfolio
        url: "#portfolio"
      -
        title: About us
        url: "#aboutus"
  footer:
    contact_us: true
    form_url: https://usebasin.com/f/d773310b9def
    socials:
      - 
        name: github
        url: "https://github.com/saifas-bi"
      -
        name: facebook
        url: "https://www.facebook.com/saifascom"
      -
        name: linkedin
        url: "https://www.linkedin.com/company/saifas/"
      -
        name: twitter
        url: "https://twitter.com/saifascom"